name: ECR images cleaner
author: zheileman
description: Cleanup images from ECR based on pushed date, keeping images in use in replica sets history.
inputs:
  ecr-repo-name:
    required: true
    description: Name of the ECR repository, usually is team-name/app-name
  additional-tags-regex:
    required: false
    default: .*main.*|.*latest.*
    description: Additional image tags that should not be deleted (regex)
  days-to-keep-old-images:
    required: false
    default: "30"
    description: Number of days to keep images, older will be purge (unless in use or in buffer)
  max-old-images-to-keep:
    required: false
    default: "25"
    description: Number of images to keep even if they are older than the cutoff date

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - run: ${{ github.action_path }}/ecr-cleanup.sh
      shell: bash
      env:
        ECR_REPO_NAME: ${{ inputs.ecr-repo-name }}
        ADDITIONAL_TAGS_REGEX: ${{ inputs.additional-tags-regex }}
        DAYS_TO_KEEP_OLD_IMAGES: ${{ inputs.days-to-keep-old-images }}
        MAX_OLD_IMAGES_TO_KEEP: ${{ inputs.max-old-images-to-keep }}
